name: CI

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install kaggle pandas

    - name: Set up Kaggle credentials
      run: |
        mkdir -p ~/.kaggle
        echo "{\"username\":\"alankaruniyal\",\"key\":\"0bbd5a8f79f781ba3fcf814f85d72d48\"}" > ~/.kaggle/kaggle.json
        chmod 600 ~/.kaggle/kaggle.json

    - name: Run pipeline and tests
      run: |
        chmod +x /project/pipeline.sh
        /project/pipeline.sh
        chmod +x /project/tests.sh
        /project/tests.sh
